### ISSUE TITLE
Graphical Structure Creation

### ISSUE THREAD

**Issue by MiguelMDSDP** [furgbol/gui#3]
Before implementing the GUI's HTTP routes, we need to create its graphical structure.

**Comment by MiguelMDSDP** [comment]
**Checklist**:
- [x] Pause/play button
- [x] Robot identifiers configuration
- [x] Maximum velocities configuration

**Comment by renantarouco** [comment]
@LucasMartinsUthi vais usar algum framework? Vai ter visualização do jogo na tela, tipo a do F180 que ficava tipo uma visão de cima?

Quando roda a aplicação do o server com o backend já vai estar rodando, já sabes como vai entregar/servir a interface? Algumas opções (independente de usar framework ou não):
- App estática HTML/CSS/Javascript hospedada num server Apache local;
- Um server implementado específico pra isso, em qualquer linguagem, só pra servir as páginas;
- Embarca na própria aplicação do FURGBol, junto com o server que serve as rotas do backend, uma rota pra servir as páginas da aplicação;
- Electron.

Me diz o que tu tá pensando em fazer e o porquê.

**Comment by renantarouco** [comment]
@MiguelMDSDP vamos especificar mais a interface assim como estamos fazendo com o backend.

A intenção é visualizar apenas o que está acontecendo no jogo, ou enviar comandos para o sistema? Pela lista que já botasse ali imagino que um certo nível de controle vai ser imlpementado, acho que a gnt precisa definir bem o nível de controle que vamos permitir pela interface, começar do nível mais raso (visualização apenas) e aos poucos ir crescendo a profundidade de controle (inicialização de sistema -> configuração de time -> configuração de robô).

Rola junto com o @LucasMartinsUthi fazer tipo um wireframe ou mockup do que vai ser a interface? Acho que com isso a gnt vai muito mais longe.

**Comment by MiguelMDSDP** [comment]
@renantarouco A intenção inicial nem era ter uma visualização do jogo pelas circunstâncias do ambiente da categoria, dado que essa interface também vai controlar a simulação, o uso de joystick, entre outros.

Como foi especificado no Trello e também aqui nas issues da GUI, na versão 1.0 do nosso software a interface vai nos oferecer um controle de pausa e continuação, bem como a configuração do ambiente de jogo (qual o papel de cada robô identificando-os por cores, qual a velocidade máxima que cada robô pode atingir, etc).

**Comment by MiguelMDSDP** [comment]
![modal](https://user-images.githubusercontent.com/31577199/74273351-11ef1f80-4cef-11ea-9718-7d704e026139.png)
![tela inicial](https://user-images.githubusercontent.com/31577199/74273355-13204c80-4cef-11ea-8e4c-2d9038cb6f3c.png)

**Comment by renantarouco** [comment]
Já especificaram algumas restrições do tipo: o sistema só pode dar play se tiver a configuração de pelo menos um robô pronta, validação dos campos (já recomendo que se faça tanto no fronte quanto no back) e essas coisas? A configuração vai junto com o _play_ ou vai ter uma rota de configuração? Pergunto porque configuração em runtime é muito mais complicado então sugiro desabilitar esses controles do environment uma vez que o sistema tenha sido dado play.

Outra sugestão pra mim é que os botões de _play_ e _pause_ não precisam coexistir, pois depois de dar play só pode dar _pause_ e o mesmo vice-versa. Também queria maiores esclarecimentos do @LucasMartinsUthi sobre o que ele vai usar pra desenvolver isso e se já começou.

**Comment by MiguelMDSDP** [comment]
@renantarouco essas são as restrições que havíamos especificado:

- A reconfiguração só pode ser feita quando o sistema estiver pausado;
- As alterações nas configurações e o botão de salvar só podem ser desbloqueadas quando o botão de reconfiguração for acionado;
- O botão de pause / play deve condizer com a situação do sistema, ou seja, quando estiver pausado a opção disponível deve ser play e vice-versa;
- Sempre que o botão de pause / play for acionado, uma requisição GET deve ser feita na rota */pause*;
- Sempre que o botão de salvar as configurações for acionado, uma requisição POST com o json padrão de configuração preenchido deve ser feita na rota */config/environment*.

**Comment by MiguelMDSDP** [comment]
@renantarouco essa era a issue apenas pra especificar a estrutura, sem desenvolvimento nenhum ainda, acredito que o @LucasMartinsUthi ainda não tenha começado, mas tem uma outra issue (#6) pra o desenvolvimento do frontend.

**Comment by renantarouco** [comment]
Beleza @MiguelMDSDP . Acho que então o botão play e pause podem ser o mesmo botão, quando clica um some e o outro aparece, e se a configuração só é feita com o sistema parado, acho que é mais coerente enviar no _play_ um post para inicio do sistema com a configuração no corpo: tu dá um play com a configuração desejada, o server lê a configuração, e inicia o sistema, não tem pq manter uma rota de configuração separada do _start/play_ já que não vai se fazer configuração runtime.

**Comment by MiguelMDSDP** [comment]
@renantarouco quanto ao botão eu concordo contigo. Porém, tu até tem um ponto em relação à configuração, mas em 2019 nosso problema era a reconfiguração geral do sistema ao dar play: isso gerava um atraso no início da movimentação dos nossos robôs e, pelo fato do jogo ser muito rápido, quando os robôs iniciavam a movimentação efetiva já era tarde demais. Tomamos muitos gols assim. Portanto, acho importante que mantenhamos essa rota de configuração pra que quando dermos play já esteja tudo nos conformes e os robôs apenas comecem a jogar de fato.

**Comment by renantarouco** [comment]
@MiguelMDSDP Perfeito. Entendi!! Esse ponto tem que ficar claro sempre que documentarmos qualquer coisa relacionada. Valeu

**Comment by LucasMartinsUthi** [comment]
@renantarouco sobre o que eu e o Miguel tínhamos discutido e o que eu tinha planejado em fazer era o seguinte.

Framework ia usar Bootstrap e Jquery ou talvez React para montar o frontend e controlar manipulação da DOM. Sobre a comunicação tinha pensado em fazer algo parecido com REST, mandando um POST  via Ajax para o servidor, ele seria responsável em controlar o ambiente e limitar  o que o usuário pode ou não fazer pela interface.

Sobre o botão, ele é um toggle, eu só desenhei a tela daquele jeito para mostrar que ele ia mudar de status, por isso a seta entre eles.

**Comment by MiguelMDSDP** [comment]
Vou fechar a issue da criação da estrutura gŕafica. Maiores discussões nas outras issues.
